#ifndef LISTERROR_H
#define LISTERROR_H

#define WRONG_DATA 1
#define WRONG_INIT_RESOURCE 2
#define WRONG_NO_GPU 3
#define WRONG_GPU_PROPERTIES 4
#define WRONG_WINDOW_CREATING 5
#define WRONG_WINDOW_NOT_READY 6
#endif // !LISTERROR_H
